spring:
  datasource:
    username: postgres
    password: FxTvtphEegnPKVASKQfkLQEcuNWOwSXA
    url: jdbc:postgresql://junction.proxy.rlwy.net:17646/railway
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database:
      postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  cache:
    type: simple
  profiles:
    hibernate:
      jdbc:
        non_contextual_creation: true