spring:
  datasource:
    username: postgres
    password: postgres_secret
    url: jdbc:postgresql://localhost:5432/mydb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database:
      postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  cache:
    type: simple