spring:
  datasource:
    url: jdbc:postgresql://amvera-hiss-cnpg-avalog-postgres-rw:5432/avalog
    username: avalog
    password: FohjRfchPYyidOVeekySoDajfnHvagum
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database:
      postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  cache:
    type: simple
  profiles:
    hibernate:
      jdbc:
        non_contextual_creation: true